# Generated by Django 4.0.5 on 2022-08-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_tag_produit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.FileField(null=True, upload_to='public'),
        ),
    ]
